# Generated by Django 5.0.3 on 2024-03-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_message',
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='sender_receiver_check',
        ),
    ]
