# Generated by Django 5.0.3 on 2024-04-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postings',
            old_name='post_type',
            new_name='typeofpost',
        ),
        migrations.RemoveField(
            model_name='postings',
            name='location',
        ),
    ]
