# Generated by Django 5.0.3 on 2024-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_message_unique_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.TextField(),
        ),
    ]
