# Generated by Django 5.0.3 on 2024-04-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_post_type_postings_typeofpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='location',
            field=models.CharField(default='', max_length=256),
        ),
    ]
