# Generated by Django 5.0.3 on 2024-03-31 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appliedfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedfor',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appliedfor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postings', unique=True),
        ),
    ]
