# Generated by Django 5.0.3 on 2024-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_skills_range_customuser_websitelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Fresher', max_length=256),
        ),
    ]
