# Generated by Django 5.0.3 on 2024-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='websitelinks',
            field=models.CharField(default=',,,,', max_length=256),
        ),
    ]
